cmd/edecan/**/*.go
internal/**/*.go
internal/http/static/**/*.css
internal/http/static/**/*.js
config.yaml
.env
Makefile
modd.conf {
  prep: "make -o generate build"
  daemon: "make CMD='bin/edecan' run-with-env"
}

internal/**/*.templ {
  prep: "make generate"
}
